spring:
    application:
        name: rapid-config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/token01/rapid-config.git


server:
    port: 8750 #启动端口
